print("中国是茶叶的原产地, 是世界上最早发现并利用茶树的国家。")
print("今取った手絶対放さないと約束したから私たち今取った手絶対放さない.")
print("‘장문’의 뜻풀이에 따르면, ‘장문’의 용례 문장은, 지적하신 대로, 의미가 겹치는 것으로 보입니다.")
print("Quand j’ai mal à la gorge, j’aime bien manger de la glace.")
print("Wer bin ich denn, dass ich mich dazu äußern soll?")
print("Я прекрасно провел с тобой время этим вечером")
print("¿Te gustaría salir a cenar un día de éstos?")

print("Δεν είμαι σίγουρος για την ημερομηνία")

print("สวัสดีครับ/สวัสดีค่ะ")
print("مرحبًا")
print("မင်္ဂလာပါ")
print("Γειά σας")
print("नमस्ते")
